version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: notion_on_the_go
    ports:
      - 5432
    volumes:
      - postgres:/data/postgres
    networks:
      - app_network
    container_name: postgres

  api:
    env_file:
      - .env
    networks:
      - app_network
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres

networks:
  app_network:
volumes:
  postgres: